### ISSUE TITLE
LayerSelector layers

### ISSUE THREAD

**Issue by stdavis** [agrc/roads.utah.gov#15]
- [x] Imagery
- [x] Hybrid
- [x] Topo
- [x] Terrian
- [x] Land Ownership
- [x] Historic 15
- [x] Historic 7.5 Historic Imagery
- [x] UDOT Historic Maps
- [x] UDOT Historic D
- [x] 76 Imagery
- [x] UtahPLSS (vector tiles cache)

**Comment by stdavis** [comment]
Hey @ZachBeck: Can you take a look at the unchecked layers in the description for this issue and let me know if they look familiar to you as one that would be on the PLPCO servers. If so, have they been moved to the newer server as raster catalogs or are they in an old image server instance?

**Comment by stdavis** [comment]
Land Ownership layer in web mercator maintained by SITLA: https://tlamap.trustlands.utah.gov/arcgis/rest/services/SpecialProject/UT_SITLA_LandOwnership_WM/MapServer

**Comment by ZachBeck** [comment]
Those are old historic topo and UDOT map image services that I created.

**Comment by stdavis** [comment]
On the old 10.0 PLPCO box?

**Comment by ZachBeck** [comment]
Yep (if I remember right). They wouldn't be too hard to redo, I'd be surprised if they even need them at all.

**Comment by stdavis** [comment]
OK. They say that they want them in the new version of the roads app so they need will need to be upgraded. Do you know if they have a newer server yet?

**Comment by ZachBeck** [comment]
I think they do but I don't know for sure.

**Comment by stdavis** [comment]
Waiting for new server from PLPCO to republish all of the image services...

**Comment by stdavis** [comment]
Waiting for raster mosaics to be built on the new server for the rest of the layers in this issue.

**Comment by stdavis** [comment]
Finished up with 5015f1ccb023430ff9b521c2926fec4252760515
