### ISSUE TITLE
Error with identifying road using search 

### ISSUE THREAD

**Issue by jwolfski** [agrc/roads.utah.gov#26]
After searching for a road using it's "Road Name"  There was an error with the roads identify task
<img width="1108" alt="screen shot 2017-12-07 at 11 53 03 am" src="https://user-images.githubusercontent.com/10835165/33732902-3ac1ff0e-db45-11e7-9bdf-b285880c9151.png">

**Comment by steveoh** [comment]
Would you open the developer tools and open the console and screenshot the errors please?

I'm happy to help you figure out how to open those things if you would tell me the browser you are using.

**Comment by stdavis** [comment]
I checked it out this morning. There's nothing helpful in the console. Digging through the code now...

**Comment by stdavis** [comment]
Looks like it only happens with logged in users. Just pushed a fix to production.

@jwolfski Thanks for using GitHub! It makes it super convenient for us. Let me know if you see any further problems with this issue or feel free to open new issues for others.
