### ISSUE TITLE
Truncated videos for longer roads

### ISSUE THREAD

**Issue by stdavis** [agrc/roads.utah.gov#37]
Opening on behalf of @jwolfski:
>The second issue I am coming across is in regards to longer roads. Such as Hole N' The Road road (RD130911). What seems to happen is any video that is longer than 17 minutes, the GPX point location does not display on the map. Try Clicking on the RD130911 road and fast forward to anything after 18 minutes and let me know if the Point location show up on the map.

**Comment by stdavis** [comment]
@jwolfski:
This was caused by ArcGIS Server defaulting to limit the number of returned points in the video service to 1000. I wrote a script that crawled the video data and returned the number of video points per RDID. The largest one was ~10,000. I increased the max number of returned records for the video service in ArcGIS Server to be 15,000.

RD130911 seems to be working correctly now. Let me know if you are still seeing otherwise.

**Comment by jwolfski** [comment]
Looks like it is working on my end. Thank you!
