### ISSUE TITLE
Data not loading on roads viewer

### ISSUE THREAD

**Issue by jwolfski** [agrc/roads.utah.gov#39]
Our team cannot get any of the data from the ArcServer/SDE to load on the roads viewer 
<img width="1152" alt="Screen Shot 2019-06-13 at 2 47 45 PM" src="https://user-images.githubusercontent.com/10835165/59466299-3f936a00-8dea-11e9-8b8b-ece04e406223.png">

**Comment by steveoh** [comment]
https://agrc-status.netlify.com/ is affecting everything. Once DTS figures it out it will start working properly again.
