### ISSUE TITLE
Class D Roads disappear

### ISSUE THREAD

**Issue by jwolfski** [agrc/roads.utah.gov#40]
The R.S2477 Class D roads are initially visible. When you zoom in on any county they disappear from view.

**Comment by stdavis** [comment]
How is it looking this morning?

**Comment by jwolfski** [comment]
Looking good. Thanks!

*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~**~~~*


[image: State of Utah]
Jason Wolf
*GIS Project Manager *

State of Utah  | Public Lands Policy Coordinating Office
m: 801.809.6340
w: publiclands.utah.gov
e: jasonwolf@utah.gov
a: 350 N State Street, SLC, UT
IMPORTANT: The contents of this email and any attachments are confidential.
It is strictly forbidden to share any part of this message with any third
party, without a written consent of the sender. If you received this
message by mistake, please reply to this message and follow with its
deletion, so that we can ensure such a mistake does not occur in the future.
