### ISSUE TITLE
Land ownership disappears when zooming

### ISSUE THREAD

**Issue by jwolfski** [agrc/roads.utah.gov#42]
Looks like users are experiencing an issue where the land ownership layer will disappear from the map when a user changes the Zoom

**Comment by steveoh** [comment]
Is the behavior happening at multiple scales or might there be a scale dependent rendering?

**Comment by jwolfski** [comment]
It looks like it might be related to a scale dependency. I can see
landownership when viewing the layer at a statewide scale but nothing past
that.

**Comment by steveoh** [comment]
If you are comfortable with the browser developer tools, is the service returning any error codes in the console or network panel?

**Comment by jwolfski** [comment]
I’m not seeing anything that specifically stands out.

**Comment by steveoh** [comment]
Ok this will help scott sort this out when he has a chance. I'm not sure I have credentials to view the application at the moment. 

If this is in fact an update to scale dependent rendering, what would you prefer the new range to be?

**Comment by jwolfski** [comment]
I’d imagine Scott has an idea. It would be the same range as all the other apps he develops that display land ownership

**Comment by steveoh** [comment]
It appears that sitla has made some changes to the service.

https://gis.trustlands.utah.gov/server/rest/services/Ownership/UT_SITLA_Ownership_LandOwnership_WM/MapServer?f=jsapi

We will have to reach out to them.

**Comment by stdavis** [comment]
I'm struggling to reproduce:
![image](https://user-images.githubusercontent.com/1326248/83077172-19cf9700-a034-11ea-9366-303980f6a15b.png)
Is this still an issue, or did SITLA fix their service?

**Comment by stdavis** [comment]
Sounds like Barry at SITLA fixed the issue with the map service and it's working correctly again.

**Comment by steveoh** [comment]
Sitla modified the service to fix an issue with their plat website. They changed the dynamic map to be cached. They will publish a new service for their website since there are many dependencies on the current service.

**Comment by jwolfski** [comment]
Looks like it is working on my end. Thank you


*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~**~~~*


[image: State of Utah]
Jason Wolf
*GIS Project Manager *

State of Utah  | Public Lands Policy Coordinating Office
m: 801.809.6340
w: publiclands.utah.gov
e: jasonwolf@utah.gov
a: 350 N State Street, SLC, UT
IMPORTANT: The contents of this email and any attachments are confidential.
It is strictly forbidden to share any part of this message with any third
party, without a written consent of the sender. If you received this
message by mistake, please reply to this message and follow with its
deletion, so that we can ensure such a mistake does not occur in the future.
