### ISSUE TITLE
Move PLPCO imagery to discover

### ISSUE THREAD

**Issue by stdavis** [agrc/roads.utah.gov#9]
@brigsz: We need to know specifically what data they want moved. Perhaps is the layers in #15?

**Comment by brigsz** [comment]
I spoke with Bert about this some time ago, I will check in with him again, but I suspect this may take a bit of effort/planning.  I am not sure if it will be feasible for this round.  I will get back to you tomorrow Jan 10

**Comment by stdavis** [comment]
Hey @brigsz: What ever happened with this?

**Comment by stdavis** [comment]
@nathankota: Do you know anything about this issue? I wonder if PLPCO still has imagery that they want moved to discover and if we even want to offer that.

**Comment by stdavis** [comment]
I'll open this back up if it ever comes up again.

**Comment by nathankota** [comment]
I haven't heard anything about this, and agree with your strategy.
